### ISSUE TITLE
Buffer() is deprecated

### ISSUE THREAD

**Issue by terris-anylog** [xompass/xompass-pi-webapi-browser#1]
I am using node 12.6.0

When I run npm start, I see the following message:

(node:57772) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by yuyomagico** [comment]
Hi terris,
It is indeed a super old code. We can update it, but still will work.

**Comment by yuyomagico** [comment]
Should be fixed now

**Comment by terris-anylog** [comment]
Thanks!!
